### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mrlitchyb** [onfoot/homebridge-valetudo-xiaomi-vacuum#10]
Just wanted to leave this here so the problem is not forgotten ;)

Did not find the issue in the code myself on first glance but this shows up when I send my vaccum back home:

```(node:2238) UnhandledPromiseRejectionWarning: ReferenceError: log is not defined
    at /usr/local/lib/node_modules/homebridge-valetudo-xiaomi-vacuum/index.js:270:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2238) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by onfoot** [comment]
Yeah, it was missing the local `log` variable, which wasn't set from `this.log` at the beginning of the `goHome` function. Fixed this too in the 0.1.4, although now I noticed that parsing the `go home` response will still fail, but at least it will actually start going home when told to. ;)

**Comment by onfoot** [comment]
Oh crap. Just found a fix for home request handling on my other computer. Will post it soon™!

**Comment by T-Bone90** [comment]
Could you make your plugin working with Valetudo RE too? :)

**Comment by onfoot** [comment]
Yeah, given the amount of requests for that I think I'll finally do it!

**Comment by onfoot** [comment]
If you're still interested, @T-Bone90, version 0.1.5 is there to check out with some updates!

And the go home response issue should be fixed as well.
