### ISSUE TITLE
Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by norspoint1991** [onfoot/homebridge-valetudo-xiaomi-vacuum#12]
Hi,
I installed the plugin and created an accessory using the following code:
"accessories": [
        {
            "name": "Bello",
            "ip": "192.168.XXX.XXX",
            "accessory": "ValetudoXiaomiVacuum"
        }
]

After that I got the following error message: "Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0"
Valetudo is reachable and the vacuum shows up in the home app but only 'Find Bello' is working. The rest is not responsive. I tried changing the order in the json file but (as expected) it did not change anything.
Thanks in advance for your help.

**Comment by onfoot** [comment]
Hi! Which version of Valetudo are you running on your robot?

**Comment by norspoint1991** [comment]
I am using Valetude RE v 0.9.6

**Comment by onfoot** [comment]
If it's not based on 0.6.0 or later, it's just not gonna work. There was recently a major change in REST API and it would be a pain for me to maintain support for both. Unless someone gets me a set of vacuums to experiment on. ;)

**Comment by norspoint1991** [comment]
Ah ok. Thanks for the info. I just realised that there is a difference between Valetudo and Valetudo RE. In that case I will install the normal version when I find the time.
Thanks for the fast anwer.
