### ISSUE TITLE
Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0 with Valetudo RE 0.9.8.1

### ISSUE THREAD

**Issue by xorguy** [onfoot/homebridge-valetudo-xiaomi-vacuum#13]
Hi.

Since few version back of Valetudo RE now homebridge complains about:
"Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0".

With previous versions was working great but since 0.9.6 or so it fails.

Any way to fix that?

**Comment by onfoot** [comment]
Hi! Is this version of Valetudo RE based on Valetudo >= 0.6.0? If not, then sorry, but I updated the way my plugin communicates with Valetudo to the updated one, which is backwards incompatible.

**Comment by xorguy** [comment]
Then maybe that's the problem, I'm not sure which valetudo is valetudo re based on. Thanks anyway.

**Comment by xorguy** [comment]
Seems valetudo RE is working fine with previous version 0.1.3, so only need to install the previous 0.1.3.

**Comment by holypetrus** [comment]
So that means I have to downgrade the plug-in? How can I do it?

**Comment by xorguy** [comment]
@holypetrus you can install specific version with 

`npm -g install homebridge-valetudo-xiaomi-vacuum@0.1.3`

**Comment by holypetrus** [comment]
Thank you! It seems to be working.

**Comment by onfoot** [comment]
Sorry it took so long, but the update is here and should work with RE.
