### ISSUE TITLE
Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by holypetrus** [onfoot/homebridge-valetudo-xiaomi-vacuum#14]
Hello,

unfortunately the plugin returns the following error for my s50 robot with valetudo:
Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0

I think it is because I use rand256 customized Valetudo-version.
https://github.com/rand256/valetudo
Can somebody help my to get rid of that error? I guess I have to change something in the plugin, because there seems to be a difference in the "current status"?

Thank you!

**Comment by Hypfer** [comment]
https://github.com/onfoot/homebridge-valetudo-xiaomi-vacuum/issues/13#issuecomment-707796377

**Comment by holypetrus** [comment]
Thank you! Even if I’m not sure what’s causing the problem :)

**Comment by hankipanky** [comment]
Valetudo RE seems to have different endpoints. `/api/state` does not exist:

```
$ curl -s -v -H "Accept: text/json" http://192.168.75.7/api/state
*   Trying 192.168.75.7...
* TCP_NODELAY set
* Connected to 192.168.75.7 (192.168.75.7) port 80 (#0)
> GET /api/state HTTP/1.1
> Host: 192.168.75.7
> User-Agent: curl/7.64.1
> Accept: text/json
> 
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 148
< Vary: Accept-Encoding
< Date: Sun, 07 Feb 2021 09:52:05 GMT
< Connection: keep-alive
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/state</pre>
</body>
</html>
```

There is [`/api/current_status`](https://github.com/rand256/valetudo/blob/testing/lib/webserver/WebServer.js#L207) though.

**Comment by onfoot** [comment]
Once you enable 'legacy-mode' in the new version 0.1.5 of this plugin, you can use Valetudo RE or an old version of The True Valetudo, @holypetrus .

Shout if there are any issues!
