### ISSUE TITLE
[XiaomiVacuum] Error parsing current status info: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Dima-Kal** [onfoot/homebridge-valetudo-xiaomi-vacuum#18]
Using latest Valetudo and Homebridge version.

**Comment by onfoot** [comment]
Yes, sorry, I'm in the process of upgrading the plugin to make it work with the 2021 release finally. Stay tuned!

**Comment by Dima-Kal** [comment]
Okay thank you very much for the response!
