### ISSUE TITLE
Check whether it's viable to expose Vacuum's map as a HomeKit camera

### ISSUE THREAD

**Issue by onfoot** [onfoot/homebridge-valetudo-xiaomi-vacuum#2]
One would need to be able to create a single-digit-fps MJPEG stream from images generated either by [I can't believe it's valetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo) or the plugin itself, then dump it using ffmpeg to HomeKit.

**Comment by onfoot** [comment]
I finally got around to toy with this and succeeded. The setup is:

1. An mqtt broker running on my home server. [hmq](https://github.com/fhmq/hmq) in my case.
2. Vacuum set up to connect to said mqtt broker.
3. [I can't believe it's valetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo) running on my camera server, with webserver enabled, running on port 3030.
4. [homebridge-camera-ffmpeg](https://www.npmjs.com/package/homebridge-camera-ffmpeg) installed on my camera server's homebridge, properly configured.
5. Camera added to Home.

`homebridge-camera-ffmpeg` config:

```
{
      "name": "Vacuum",
      "videoConfig": {
        "source": "-loop 1 -i http://localhost:3030/api/map/image",
        "videoFilter": "pad='ih*16/9:ih:(ow-iw)/2:(oh-ih)/2',scale=1920:1080",
        "maxFPS": 5
      }
}
```

- `-loop 1` sets up ffmpeg so it's constantly loading the generated png for each frame
- `pad` filter is set up so it expands the generated png to an 16:9 aspect ratio image so it looks right in Home app, then it's scaled using `scale` down to 1920x1080
- `maxFPS` set to a reasonable value; at `1` it was having hard time to start live streaming in Home app; at `5` it's instantaneous

Looks cool!

**Comment by heberlej** [comment]
Would you please a step by step guide, this would be awesome :)
