### ISSUE TITLE
spot cleaning?

### ISSUE THREAD

**Issue by pcace** [onfoot/homebridge-valetudo-xiaomi-vacuum#25]
Hi there, 
i see there is an option to spot-clean. but how is that supposed to work? 

Cheers and thanks!

**Comment by onfoot** [comment]
Hi! It's supposed to start the same function as the spot cleaning button on the robot, but in retrospect I think it's kind of useless, since in order to spot clean, you need to move the vacuum to said spot, so you just as well can push that dang button. 😃

**Comment by pcace** [comment]
ok i see! thanks for the explanation
