### ISSUE TITLE
crash during cleanup

### ISSUE THREAD

**Issue by leonardpitzu** [onfoot/homebridge-valetudo-xiaomi-vacuum#5]
TypeError: this.sendJSONRequest(...).then(...).catch(...).finally is not a function
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at ValetudoXiaomiVacuum.startCleaning (/mnt/usb/homebridge/homebridge-valetudo-xiaomi-vacuum/index.js:287:25)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at emitMany (events.js:147:13)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at Characteristic.On.emit (events.js:224:7)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at Characteristic.On.Characteristic.setValue (/usr/lib/node/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at Bridge.<anonymous> (/usr/lib/node/homebridge/node_modules/hap-nodejs/lib/Accessory.js:880:22)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at Array.forEach (<anonymous>)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node/homebridge/node_modules/hap-nodejs/lib/Accessory.js:820:8)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at emitMany (events.js:147:13)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at HAPServer.emit (events.js:224:7)
Thu May  2 18:00:50 2019 daemon.err homebridge[5439]:     at HAPServer._handleCharacteristics (/usr/lib/node/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)

**Comment by onfoot** [comment]
Which version are you running?

**Comment by leonardpitzu** [comment]
0.0.5

**Comment by onfoot** [comment]
Sorry, got carried away there a bit. A fix is coming.

**Comment by onfoot** [comment]
`0.1.1` is on its way.

Seems I really have to get myself a Node v8 environment after all. ;)

**Comment by leonardpitzu** [comment]
seems to works, thanks! you can close it (will reopen if i see some other error).
