### ISSUE TITLE
No entry in Homekit with Valetudo 4.0 with FW 3.3.9

### ISSUE THREAD

**Issue by vanderLo** [onfoot/homebridge-valetudo-xiaomi-vacuum#6]
Doesn't seem to work with Valetudo 4.0 with FW 3.3.9. Homebridge doesn't give me an error, but I don't see an entry in iOS 12 Home App.

Does it need an update?

**Comment by onfoot** [comment]
I have a git version of Valetudo from a few weeks back on my vacuum, so theoretically it's almost a 0.4.0 one and I have no issues, but I'll try to make an update and see if any come up. :)

**Comment by vanderLo** [comment]
It's resolved, I made a mistake during config.

**Comment by onfoot** [comment]
Thanks for the follow-up! I haven't managed to upgrade my robot yet due to lack of time. 😭
